name: Docker Image CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build images
              run: ci/build.sh
            - name: Deploy images
              env:
                  DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
                  DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
              run: ci/push.sh
